version: "3.9"

services:

  monitor_support:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: monitor_support

    env_file:
      - .env

    volumes:
      - ./.auth:/root/ocr_extraction/monitor_support/.auth
      - ./output:/root/ocr_extraction/monitor_support/output
      - ./state.json:/root/ocr_extraction/monitor_support/state.json
      - /tmp:/tmp

    working_dir: /root/ocr_extraction/monitor_support

    restart: unless-stopped